"""Collect runs/*/s*/metrics.json into a markdown table (mean ± std over seeds).

    python scripts/summarise_runs.py [--runs runs] [--out docs/results.md] [--sort]
"""
from __future__ import annotations

import argparse
import json
import statistics as st
from collections import defaultdict
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--out", default="docs/results.md")
    ap.add_argument("--sort", action="store_true", help="sort by mean val acc instead of run time")
    args = ap.parse_args()

    by_name = defaultdict(list)
    for mf in sorted(Path(args.runs).glob("*/s*/metrics.json"), key=lambda p: p.stat().st_mtime):
        m = json.loads(mf.read_text())
        by_name[m["name"]].append(m)

    rows = []
    for name, ms in by_name.items():
        accs = [m["best_val_acc"] * 100 for m in ms]
        m0 = ms[0]
        rows.append({
            "name": name, "n": len(ms),
            "mean": st.mean(accs), "std": st.stdev(accs) if len(accs) > 1 else 0.0,
            "min": min(accs), "max": max(accs),
            "model": m0["model"], "pre": m0["pretrained"], "color": m0["color"], "aug": m0["aug"],
            "res": m0["img_size"], "ep": m0["epochs"], "lr": m0["lr"],
            "mix": f"{m0['mixup']}/{m0['cutmix']}" if (m0["mixup"] or m0["cutmix"]) else "-",
            "ls": m0["label_smoothing"], "wd": m0["weight_decay"], "ema": "y" if m0["ema"] else "-",
            "params": m0["params_M"], "ips": m0["eval_img_per_sec"], "min_": st.mean(m["minutes"] for m in ms),
        })
    if args.sort:
        rows.sort(key=lambda r: -r["mean"])

    hdr = ["run", "seeds", "val acc % (mean ± std)", "range", "model", "pretrained", "color", "aug",
           "res", "epochs", "lr", "mix/cutmix", "label smooth", "wd", "ema", "params M", "img/s", "min/run"]
    lines = ["| " + " | ".join(hdr) + " |", "|" + "---|" * len(hdr)]
    for r in rows:
        lines.append("| " + " | ".join([
            r["name"], str(r["n"]), f"{r['mean']:.2f} ± {r['std']:.2f}" if r["n"] > 1 else f"{r['mean']:.2f}",
            f"{r['min']:.1f}–{r['max']:.1f}" if r["n"] > 1 else "", r["model"], r["pre"], r["color"], r["aug"],
            str(r["res"]), str(r["ep"]), f"{r['lr']:g}", r["mix"], f"{r['ls']:g}", f"{r['wd']:g}", r["ema"],
            f"{r['params']:.1f}", f"{r['ips']:.0f}", f"{r['min_']:.1f}"]) + " |")
    table = "\n".join(lines)
    print(table)
    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text("# Experiment results (validation set, 480 images)\n\n"
                                  "Generated by `scripts/summarise_runs.py`. One image = 0.21%.\n\n" + table + "\n")


if __name__ == "__main__":
    main()
